[server]
headless = true
address = "0.0.0.0"
port = 7860
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false

[theme]
base = "dark"

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
